#version 460

layout (local_size_x = 16, local_size_y = 16) in;

layout(rgba16f,set = 0, binding = 0) uniform image2D image;

layout(push_constant) uniform PushConstants
{
    float time;
} pc;

void main()
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(image);

    if(texelCoord.x < size.x && texelCoord.y < size.y)
    {
        vec4 color = vec4(0.0, 0.0, 0.0, 1.0);

        if(gl_LocalInvocationID.x != 0 && gl_LocalInvocationID.y != 0)
        {
            vec2 uv = vec2(texelCoord) / vec2(size);

            float noise = sin(uv.x * 10.0 + pc.time)
            * sin(uv.y * 5.0 - pc.time * 2.0);

            float intensity = smoothstep(0.2, 0.8, noise);

            color.rgb = vec3(1.5, 0.5, 0.1) * intensity;
        }

        imageStore(image, texelCoord, color);
    }
}
