#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require

#include "bindless.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(push_constant) uniform PushConstants
{
    uint eqTextureIdx;
    uint skyboxIdx;
} pc;

const vec2 invAtan = vec2(0.1591, 0.3183);

vec2 sampleSphericalMap(vec3 v)
{
    vec2 uv = vec2(atan(v.z, v.x), asin(v.y));
    uv *= invAtan;
    uv += 0.5;
    return uv;
}

vec3 getCubemapDirection(vec2 uv, int face)
{
    switch(face)
    {
        case 0: return normalize(vec3( 1.0, -uv.y, -uv.x)); // +X
        case 1: return normalize(vec3(-1.0, -uv.y,  uv.x)); // -X
        case 2: return normalize(vec3( uv.x,  1.0,  uv.y)); // +Y
        case 3: return normalize(vec3( uv.x, -1.0, -uv.y)); // -Y
        case 4: return normalize(vec3( uv.x, -uv.y,  1.0)); // +Z
        case 5: return normalize(vec3(-uv.x, -uv.y, -1.0)); // -Z
    }

    return vec3(0.0);
}

layout(set = 1, binding = 1, rgba16f) uniform imageCube cubeImages[];

void main()
{
    ivec3 coord = ivec3(gl_GlobalInvocationID.xyz);

    ivec2 size = imageSize(cubeImages[pc.skyboxIdx]);

    int face = coord.z;

    if(coord.x >= size.x ||
    coord.y >= size.y ||
    face >= 6)
    {
        return;
    }

    vec2 uv = (vec2(coord.xy) + 0.5) / vec2(size);
    uv = uv * 2.0 - 1.0;

    uv.y *= -1.0;

    vec3 dir = getCubemapDirection(uv, face);

    vec2 sphericalUV = sampleSphericalMap(dir);

    vec3 color = texture(textures[pc.eqTextureIdx], sphericalUV).rgb;

    imageStore(cubeImages[pc.skyboxIdx], coord, vec4(color, 1.0));
}