#version 460
#extension GL_GOOGLE_include_directive : require
#include "bindless.glsl"

layout (local_size_x = 16, local_size_y = 16) in;

layout(push_constant) uniform PushConstants
{
    float time;
} pc;

void main()
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(rgba8Images[0]);

    if(texelCoord.x < size.x && texelCoord.y < size.y)
    {
        vec4 color = vec4(0.4, 0.5, 0.75, 1.0);

        //if(gl_LocalInvocationID.x != 0 && gl_LocalInvocationID.y != 0)
        /*{
            vec2 uv = vec2(texelCoord) / vec2(size);

            float noise = sin(uv.x * 10.0 + pc.time)
            * sin(uv.y * 5.0 - pc.time * 2.0);

            float intensity = smoothstep(0.2, 0.8, noise);

            color.rgb = vec3(1.5, 0.5, 0.1) * intensity;
        }*/

        imageStore(rgba8Images[0], texelCoord, color);
    }
}
