#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require

#include "bindless.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(push_constant) uniform PushConstants
{
    uint eqTextureIdx;
    uint skyboxIdx;
    uint conMapIdx;
    uint prefilterMapIdx;
    uint prefilterBaseWidth;
    uint prefilterBaseHeight;
    float roughness;
} pc;

const float PI = 3.14159265359;

vec3 getCubemapDirection(vec2 uv, int face)
{
    switch(face)
    {
        case 0: return normalize(vec3( 1.0, -uv.y, -uv.x)); // +X
        case 1: return normalize(vec3(-1.0, -uv.y,  uv.x)); // -X
        case 2: return normalize(vec3( uv.x, 1.0, uv.y));   // +Y
        case 3: return normalize(vec3( uv.x,-1.0,-uv.y));   // -Y
        case 4: return normalize(vec3( uv.x, -uv.y, 1.0));   // +Z
        case 5: return normalize(vec3(-uv.x, -uv.y,-1.0));   // -Z
    }
    return vec3(0.0);
}

void main()
{
    ivec3 coord = ivec3(gl_GlobalInvocationID.xyz);

    ivec2 size = imageSize(cubeImages[pc.conMapIdx]);
    int face = coord.z;

    if (coord.x >= size.x || coord.y >= size.y || face >= 6)
    return;

    //direction for this cubemap texel
    vec2 uv = (vec2(coord.xy) + 0.5) / vec2(size);
    uv = uv * 2.0 - 1.0;

    vec3 normal = getCubemapDirection(uv, face);

    //build tangent basis
    vec3 up = vec3(0.0, 1.0, 0.0);

    vec3 right = normalize(cross(up, normal));
    up = normalize(cross(normal, right));

    vec3 irradiance = vec3(0.0);

    float sampleDelta = 0.025;
    float nrSamples = 0.0;

    for (float phi = 0.0; phi < 2.0 * PI; phi += sampleDelta)
    {
        for (float theta = 0.0; theta < 0.5 * PI; theta += sampleDelta)
        {
            vec3 tangentSample = vec3(
            sin(theta) * cos(phi),
            sin(theta) * sin(phi),
            cos(theta)
            );

            vec3 sampleVec =
            tangentSample.x * right +
            tangentSample.y * up +
            tangentSample.z * normal;

            //sample environment map
            vec3 envColor = sampleWithIdx(pc.skyboxIdx, LINEAR_SAMPLER_CLAMPED_INDEX, sampleVec).rgb;

            irradiance += envColor * cos(theta) * sin(theta);
            nrSamples++;
        }
    }

    irradiance = PI * irradiance * (1.0 / nrSamples);

    imageStore(cubeImages[pc.conMapIdx], coord, vec4(irradiance, 1.0));
}